version: 2
updates:
  - package-ecosystem: docker
    directory: "/java/appdynamics/"
    schedule:
      interval: daily
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
    groups:
      github-actions:
        patterns:
          - "*"
